### ISSUE TITLE
Public Beta

### ISSUE THREAD

**Issue by joshxyzhimself** [joshxyzhimself/studio#1]
#### Tasks

- [ ] Studio Server folder
- [ ] Studio Client folder
- [ ] Studio Agent folder
- [ ] Studio Agent connects to Docker Socket
- [ ] Studio Agent connects to Studio Server
- [ ] User can sign-up
- [ ] User can sign-in
- [ ] User can create a server instance
- [ ] User can start / stop server instance
- [ ] User can start / stop Crestfall Authentication API
- [ ] User can serve web app that uses the Crestfall Authentication API
- [ ] User's end-users (lol) can sign-up and sign-in

#### Notes

- None.
